language: python
services:
  - docker
python:
  - "2.7"
install:
  - make deps
script:
  - make lint
  - make test_xunit
  - make docker_build
  - make docker_run
  - sleep 3; make test_api # TODO: 3 razy odpytywać API z sleep 0,5s
after_success:
  - make docker_push

deploy:
  provider: heroku
  app: desolate-river-81743
  api_key: ${HEROKU_API_KEY}
